Document: appscale-haproxy
Title: Debian appscale-haproxy Manual
Author: <insert document author here>
Abstract: This manual describes what appscale-haproxy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/appscale-haproxy/appscale-haproxy.sgml.gz

Format: postscript
Files: /usr/share/doc/appscale-haproxy/appscale-haproxy.ps.gz

Format: text
Files: /usr/share/doc/appscale-haproxy/appscale-haproxy.text.gz

Format: HTML
Index: /usr/share/doc/appscale-haproxy/html/index.html
Files: /usr/share/doc/appscale-haproxy/html/*.html
